name: Ejecucion de Pruebas Reto 3
on:
  push:
    branches: [ main, master ] # Se activa al subir cambios
  workflow_dispatch: # Permite que lo corras manualmente t√∫

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar Pruebas Cucumber BDD
        run: npm test

      - name: Ejecutar Pruebas Playwright API
        run: npx playwright test

      - name: Subir Reporte de Resultados
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-playwright
          path: playwright-report/